WorkflowLimit = '200'
WorkflowExecutionConcurrencyLimit = '200'
GatewayIncomingPayloadSizeLimit = '1mb'
VaultCiphertextSizeLimit = '2kb'
VaultIdentifierKeySizeLimit = '64b'
VaultIdentifierOwnerSizeLimit = '64b'
VaultIdentifierNamespaceSizeLimit = '64b'
VaultPluginBatchSizeLimit = '20'
VaultRequestBatchSizeLimit = '10'

[PerOrg]
ZeroBalancePruningTimeout = '24h0m0s'

[PerOwner]
WorkflowExecutionConcurrencyLimit = '5'
VaultSecretsLimit = '100'

[PerWorkflow]
TriggerRegistrationsTimeout = '10s'
TriggerSubscriptionTimeout = '15s'
TriggerSubscriptionLimit = '10'
TriggerEventQueueLimit = '50'
TriggerEventQueueTimeout = '10m0s'
CapabilityConcurrencyLimit = '30'
CapabilityCallTimeout = '3m0s'
SecretsConcurrencyLimit = '5'
ExecutionConcurrencyLimit = '5'
ExecutionTimeout = '5m0s'
ExecutionResponseLimit = '100kb'
WASMMemoryLimit = '100mb'
WASMBinarySizeLimit = '100mb'
WASMCompressedBinarySizeLimit = '20mb'
WASMConfigSizeLimit = '1mb'
WASMSecretsSizeLimit = '1mb'
LogLineLimit = '1kb'
LogEventLimit = '1000'

[PerWorkflow.ChainAllowed]
Default = 'false'

[PerWorkflow.ChainAllowed.Values]
12922642891491394802 = 'true'
12463857294658392847 = 'true'
3379446385462418246 = 'true'

[PerWorkflow.CRONTrigger]
FastestScheduleInterval = '30s'

[PerWorkflow.HTTPTrigger]
RateLimit = 'every30s:3'

[PerWorkflow.LogTrigger]
EventRateLimit = 'every6s:10'
EventSizeLimit = '5kb'
FilterAddressLimit = '5'
FilterTopicsPerSlotLimit = '10'

[PerWorkflow.ChainWrite]
TargetsLimit = '10'
ReportSizeLimit = '5kb'

[PerWorkflow.ChainWrite.EVM]
TransactionGasLimit = '5000000'

[PerWorkflow.ChainWrite.EVM.GasLimit]
Default = '5000000'

[PerWorkflow.ChainWrite.EVM.GasLimit.Values]
12922642891491394802 = '50000000'
3379446385462418246 = '10000000'

[PerWorkflow.ChainRead]
CallLimit = '10'
LogQueryBlockLimit = '100'
PayloadSizeLimit = '5kb'

[PerWorkflow.Consensus]
ObservationSizeLimit = '100kb'
CallLimit = '20'

[PerWorkflow.HTTPAction]
CallLimit = '5'
CacheAgeLimit = '10m0s'
ConnectionTimeout = '10s'
RequestSizeLimit = '10kb'
ResponseSizeLimit = '100kb'
